//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.06 at 04:52:01 PM BRST 
//


package br.gov.servicos.legado;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for canalPrestacaoServicoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="canalPrestacaoServicoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tipoCanalPrestacaoServico" type="{}tipoCanalPrestacaoServicoType"/>
 *         &lt;element name="descricao" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "canalPrestacaoServicoType", propOrder = {
    "tipoCanalPrestacaoServico",
    "descricao",
    "url"
})
public class CanalPrestacaoServicoType {

    @XmlElement(required = true)
    protected TipoCanalPrestacaoServicoType tipoCanalPrestacaoServico;
    @XmlElement(required = true)
    protected String descricao;
    @XmlElement(required = true)
    protected String url;

    /**
     * Gets the value of the tipoCanalPrestacaoServico property.
     * 
     * @return
     *     possible object is
     *     {@link TipoCanalPrestacaoServicoType }
     *     
     */
    public TipoCanalPrestacaoServicoType getTipoCanalPrestacaoServico() {
        return tipoCanalPrestacaoServico;
    }

    /**
     * Sets the value of the tipoCanalPrestacaoServico property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoCanalPrestacaoServicoType }
     *     
     */
    public void setTipoCanalPrestacaoServico(TipoCanalPrestacaoServicoType value) {
        this.tipoCanalPrestacaoServico = value;
    }

    /**
     * Gets the value of the descricao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescricao() {
        return descricao;
    }

    /**
     * Sets the value of the descricao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescricao(String value) {
        this.descricao = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }

}
