//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.06 at 04:52:01 PM BRST 
//


package br.gov.servicos.legado;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for eventoslinhaDaVidaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="eventoslinhaDaVidaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eventolinhaDaVida" type="{}eventolinhaDaVidaType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eventoslinhaDaVidaType", propOrder = {
    "eventolinhaDaVida"
})
class EventoslinhaDaVidaType {

    protected List<EventolinhaDaVidaType> eventolinhaDaVida;

    /**
     * Gets the value of the eventolinhaDaVida property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eventolinhaDaVida property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEventolinhaDaVida().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EventolinhaDaVidaType }
     * 
     * 
     */
    public List<EventolinhaDaVidaType> getEventolinhaDaVida() {
        if (eventolinhaDaVida == null) {
            eventolinhaDaVida = new ArrayList<EventolinhaDaVidaType>();
        }
        return this.eventolinhaDaVida;
    }

}
