//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.03 at 06:08:01 PM BRST 
//


package br.gov.servicos.legado;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Dados }
     * 
     */
    public Dados createDados() {
        return new Dados();
    }

    /**
     * Create an instance of {@link Dados.PortaisServico }
     * 
     */
    public Dados.PortaisServico createDadosPortaisServico() {
        return new Dados.PortaisServico();
    }

    /**
     * Create an instance of {@link Dados.PortaisServico.PortalServico }
     * 
     */
    public Dados.PortaisServico.PortalServico createDadosPortaisServicoPortalServico() {
        return new Dados.PortaisServico.PortalServico();
    }

    /**
     * Create an instance of {@link Dados.Ouvidorias }
     * 
     */
    public Dados.Ouvidorias createDadosOuvidorias() {
        return new Dados.Ouvidorias();
    }

    /**
     * Create an instance of {@link Dados.Ouvidorias.Ouvidoria }
     * 
     */
    public Dados.Ouvidorias.Ouvidoria createDadosOuvidoriasOuvidoria() {
        return new Dados.Ouvidorias.Ouvidoria();
    }

    /**
     * Create an instance of {@link Dados.Orgaos }
     * 
     */
    public Dados.Orgaos createDadosOrgaos() {
        return new Dados.Orgaos();
    }

    /**
     * Create an instance of {@link Dados.Servicos }
     * 
     */
    public Dados.Servicos createDadosServicos() {
        return new Dados.Servicos();
    }

    /**
     * Create an instance of {@link Dados.Servicos.Servico }
     * 
     */
    public Dados.Servicos.Servico createDadosServicosServico() {
        return new Dados.Servicos.Servico();
    }

    /**
     * Create an instance of {@link Dados.Servicos.Servico.AreasInteresse }
     * 
     */
    public Dados.Servicos.Servico.AreasInteresse createDadosServicosServicoAreasInteresse() {
        return new Dados.Servicos.Servico.AreasInteresse();
    }

    /**
     * Create an instance of {@link Dados.Servicos.Servico.PublicosAlvo }
     * 
     */
    public Dados.Servicos.Servico.PublicosAlvo createDadosServicosServicoPublicosAlvo() {
        return new Dados.Servicos.Servico.PublicosAlvo();
    }

    /**
     * Create an instance of {@link Dados.Servicos.Servico.PublicosAlvo.PublicoAlvo }
     * 
     */
    public Dados.Servicos.Servico.PublicosAlvo.PublicoAlvo createDadosServicosServicoPublicosAlvoPublicoAlvo() {
        return new Dados.Servicos.Servico.PublicosAlvo.PublicoAlvo();
    }

    /**
     * Create an instance of {@link Dados.Servicos.Servico.PublicosAlvo.PublicoAlvo.LinhasDaViva }
     * 
     */
    public Dados.Servicos.Servico.PublicosAlvo.PublicoAlvo.LinhasDaViva createDadosServicosServicoPublicosAlvoPublicoAlvoLinhasDaViva() {
        return new Dados.Servicos.Servico.PublicosAlvo.PublicoAlvo.LinhasDaViva();
    }

    /**
     * Create an instance of {@link Dados.Servicos.Servico.PublicosAlvo.PublicoAlvo.LinhasDaViva.LinhaDaVida }
     * 
     */
    public Dados.Servicos.Servico.PublicosAlvo.PublicoAlvo.LinhasDaViva.LinhaDaVida createDadosServicosServicoPublicosAlvoPublicoAlvoLinhasDaVivaLinhaDaVida() {
        return new Dados.Servicos.Servico.PublicosAlvo.PublicoAlvo.LinhasDaViva.LinhaDaVida();
    }

    /**
     * Create an instance of {@link Dados.Servicos.Servico.PublicosAlvo.PublicoAlvo.LinhasDaViva.LinhaDaVida.EventoslinhaDaVida }
     * 
     */
    public Dados.Servicos.Servico.PublicosAlvo.PublicoAlvo.LinhasDaViva.LinhaDaVida.EventoslinhaDaVida createDadosServicosServicoPublicosAlvoPublicoAlvoLinhasDaVivaLinhaDaVidaEventoslinhaDaVida() {
        return new Dados.Servicos.Servico.PublicosAlvo.PublicoAlvo.LinhasDaViva.LinhaDaVida.EventoslinhaDaVida();
    }

    /**
     * Create an instance of {@link Dados.Servicos.Servico.CanaisPrestacaoServico }
     * 
     */
    public Dados.Servicos.Servico.CanaisPrestacaoServico createDadosServicosServicoCanaisPrestacaoServico() {
        return new Dados.Servicos.Servico.CanaisPrestacaoServico();
    }

    /**
     * Create an instance of {@link Dados.Servicos.Servico.CanaisPrestacaoServico.CanalPrestacaoServico }
     * 
     */
    public Dados.Servicos.Servico.CanaisPrestacaoServico.CanalPrestacaoServico createDadosServicosServicoCanaisPrestacaoServicoCanalPrestacaoServico() {
        return new Dados.Servicos.Servico.CanaisPrestacaoServico.CanalPrestacaoServico();
    }

    /**
     * Create an instance of {@link Dados.PortaisServico.PortalServico.Uf }
     * 
     */
    public Dados.PortaisServico.PortalServico.Uf createDadosPortaisServicoPortalServicoUf() {
        return new Dados.PortaisServico.PortalServico.Uf();
    }

    /**
     * Create an instance of {@link Dados.Ouvidorias.Ouvidoria.Orgao }
     * 
     */
    public Dados.Ouvidorias.Ouvidoria.Orgao createDadosOuvidoriasOuvidoriaOrgao() {
        return new Dados.Ouvidorias.Ouvidoria.Orgao();
    }

    /**
     * Create an instance of {@link Dados.Orgaos.Orgao }
     * 
     */
    public Dados.Orgaos.Orgao createDadosOrgaosOrgao() {
        return new Dados.Orgaos.Orgao();
    }

    /**
     * Create an instance of {@link Dados.Servicos.Servico.OrgaoResponsavel }
     * 
     */
    public Dados.Servicos.Servico.OrgaoResponsavel createDadosServicosServicoOrgaoResponsavel() {
        return new Dados.Servicos.Servico.OrgaoResponsavel();
    }

    /**
     * Create an instance of {@link Dados.Servicos.Servico.OrgaoPrestador }
     * 
     */
    public Dados.Servicos.Servico.OrgaoPrestador createDadosServicosServicoOrgaoPrestador() {
        return new Dados.Servicos.Servico.OrgaoPrestador();
    }

    /**
     * Create an instance of {@link Dados.Servicos.Servico.AreasInteresse.Area }
     * 
     */
    public Dados.Servicos.Servico.AreasInteresse.Area createDadosServicosServicoAreasInteresseArea() {
        return new Dados.Servicos.Servico.AreasInteresse.Area();
    }

    /**
     * Create an instance of {@link Dados.Servicos.Servico.PublicosAlvo.PublicoAlvo.LinhasDaViva.LinhaDaVida.EventoslinhaDaVida.EventolinhaDaVida }
     * 
     */
    public Dados.Servicos.Servico.PublicosAlvo.PublicoAlvo.LinhasDaViva.LinhaDaVida.EventoslinhaDaVida.EventolinhaDaVida createDadosServicosServicoPublicosAlvoPublicoAlvoLinhasDaVivaLinhaDaVidaEventoslinhaDaVidaEventolinhaDaVida() {
        return new Dados.Servicos.Servico.PublicosAlvo.PublicoAlvo.LinhasDaViva.LinhaDaVida.EventoslinhaDaVida.EventolinhaDaVida();
    }

    /**
     * Create an instance of {@link Dados.Servicos.Servico.CanaisPrestacaoServico.CanalPrestacaoServico.TipoCanalPrestacaoServico }
     * 
     */
    public Dados.Servicos.Servico.CanaisPrestacaoServico.CanalPrestacaoServico.TipoCanalPrestacaoServico createDadosServicosServicoCanaisPrestacaoServicoCanalPrestacaoServicoTipoCanalPrestacaoServico() {
        return new Dados.Servicos.Servico.CanaisPrestacaoServico.CanalPrestacaoServico.TipoCanalPrestacaoServico();
    }

}
