//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.06 at 04:52:01 PM BRST 
//


package br.gov.servicos.legado;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.gov.servicos.legado package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Dados_QNAME = new QName("", "dados");
    private final static QName _PublicosAlvoTypePublicoAlvo_QNAME = new QName("", "publicoAlvo");
    private final static QName _ServicoTypeInformacoesUteisInformacaoUtil_QNAME = new QName("", "informacaoUtil");
    private final static QName _ServicoTypeRequisitosRequisito_QNAME = new QName("", "requisito");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.gov.servicos.legado
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ServicoType }
     * 
     */
    public ServicoType createServicoType() {
        return new ServicoType();
    }

    /**
     * Create an instance of {@link DadosType }
     * 
     */
    public DadosType createDadosType() {
        return new DadosType();
    }

    /**
     * Create an instance of {@link PublicoAlvoType }
     * 
     */
    public PublicoAlvoType createPublicoAlvoType() {
        return new PublicoAlvoType();
    }

    /**
     * Create an instance of {@link UfType }
     * 
     */
    public UfType createUfType() {
        return new UfType();
    }

    /**
     * Create an instance of {@link CanalPrestacaoServicoType }
     * 
     */
    public CanalPrestacaoServicoType createCanalPrestacaoServicoType() {
        return new CanalPrestacaoServicoType();
    }

    /**
     * Create an instance of {@link RequisitoType }
     * 
     */
    public RequisitoType createRequisitoType() {
        return new RequisitoType();
    }

    /**
     * Create an instance of {@link TipoCanalPrestacaoServicoType }
     * 
     */
    public TipoCanalPrestacaoServicoType createTipoCanalPrestacaoServicoType() {
        return new TipoCanalPrestacaoServicoType();
    }

    /**
     * Create an instance of {@link TipoInformacaoUtilType }
     * 
     */
    public TipoInformacaoUtilType createTipoInformacaoUtilType() {
        return new TipoInformacaoUtilType();
    }

    /**
     * Create an instance of {@link AreaType }
     * 
     */
    public AreaType createAreaType() {
        return new AreaType();
    }

    /**
     * Create an instance of {@link OuvidoriaType }
     * 
     */
    public OuvidoriaType createOuvidoriaType() {
        return new OuvidoriaType();
    }

    /**
     * Create an instance of {@link MunicipioType }
     * 
     */
    public MunicipioType createMunicipioType() {
        return new MunicipioType();
    }

    /**
     * Create an instance of {@link LinhaDaVidaType }
     * 
     */
    public LinhaDaVidaType createLinhaDaVidaType() {
        return new LinhaDaVidaType();
    }

    /**
     * Create an instance of {@link CanaisPrestacaoServicoType }
     * 
     */
    public CanaisPrestacaoServicoType createCanaisPrestacaoServicoType() {
        return new CanaisPrestacaoServicoType();
    }

    /**
     * Create an instance of {@link LinhasDaVivaType }
     * 
     */
    public LinhasDaVivaType createLinhasDaVivaType() {
        return new LinhasDaVivaType();
    }

    /**
     * Create an instance of {@link OuvidoriasType }
     * 
     */
    public OuvidoriasType createOuvidoriasType() {
        return new OuvidoriasType();
    }

    /**
     * Create an instance of {@link AreasInteresseType }
     * 
     */
    public AreasInteresseType createAreasInteresseType() {
        return new AreasInteresseType();
    }

    /**
     * Create an instance of {@link InformacoesUteisType }
     * 
     */
    public InformacoesUteisType createInformacoesUteisType() {
        return new InformacoesUteisType();
    }

    /**
     * Create an instance of {@link PortalServicoType }
     * 
     */
    public PortalServicoType createPortalServicoType() {
        return new PortalServicoType();
    }

    /**
     * Create an instance of {@link OrgaoType }
     * 
     */
    public OrgaoType createOrgaoType() {
        return new OrgaoType();
    }

    /**
     * Create an instance of {@link InformacaoUtilType }
     * 
     */
    public InformacaoUtilType createInformacaoUtilType() {
        return new InformacaoUtilType();
    }

    /**
     * Create an instance of {@link OrgaosType }
     * 
     */
    public OrgaosType createOrgaosType() {
        return new OrgaosType();
    }

    /**
     * Create an instance of {@link OrgaoPrestadorType }
     * 
     */
    public OrgaoPrestadorType createOrgaoPrestadorType() {
        return new OrgaoPrestadorType();
    }

    /**
     * Create an instance of {@link EventoslinhaDaVidaType }
     * 
     */
    public EventoslinhaDaVidaType createEventoslinhaDaVidaType() {
        return new EventoslinhaDaVidaType();
    }

    /**
     * Create an instance of {@link OrgaoResponsavelType }
     * 
     */
    public OrgaoResponsavelType createOrgaoResponsavelType() {
        return new OrgaoResponsavelType();
    }

    /**
     * Create an instance of {@link PortaisServicoType }
     * 
     */
    public PortaisServicoType createPortaisServicoType() {
        return new PortaisServicoType();
    }

    /**
     * Create an instance of {@link EventolinhaDaVidaType }
     * 
     */
    public EventolinhaDaVidaType createEventolinhaDaVidaType() {
        return new EventolinhaDaVidaType();
    }

    /**
     * Create an instance of {@link PublicosAlvoType }
     * 
     */
    public PublicosAlvoType createPublicosAlvoType() {
        return new PublicosAlvoType();
    }

    /**
     * Create an instance of {@link ServicosType }
     * 
     */
    public ServicosType createServicosType() {
        return new ServicosType();
    }

    /**
     * Create an instance of {@link RequisitosType }
     * 
     */
    public RequisitosType createRequisitosType() {
        return new RequisitosType();
    }

    /**
     * Create an instance of {@link ServicoType.Requisitos }
     * 
     */
    public ServicoType.Requisitos createServicoTypeRequisitos() {
        return new ServicoType.Requisitos();
    }

    /**
     * Create an instance of {@link ServicoType.InformacoesUteis }
     * 
     */
    public ServicoType.InformacoesUteis createServicoTypeInformacoesUteis() {
        return new ServicoType.InformacoesUteis();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DadosType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dados")
    public JAXBElement<DadosType> createDados(DadosType value) {
        return new JAXBElement<DadosType>(_Dados_QNAME, DadosType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PublicoAlvoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "publicoAlvo", scope = PublicosAlvoType.class)
    public JAXBElement<PublicoAlvoType> createPublicosAlvoTypePublicoAlvo(PublicoAlvoType value) {
        return new JAXBElement<PublicoAlvoType>(_PublicosAlvoTypePublicoAlvo_QNAME, PublicoAlvoType.class, PublicosAlvoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InformacaoUtilType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "informacaoUtil", scope = ServicoType.InformacoesUteis.class)
    public JAXBElement<InformacaoUtilType> createServicoTypeInformacoesUteisInformacaoUtil(InformacaoUtilType value) {
        return new JAXBElement<InformacaoUtilType>(_ServicoTypeInformacoesUteisInformacaoUtil_QNAME, InformacaoUtilType.class, ServicoType.InformacoesUteis.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequisitoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "requisito", scope = ServicoType.Requisitos.class)
    public JAXBElement<RequisitoType> createServicoTypeRequisitosRequisito(RequisitoType value) {
        return new JAXBElement<RequisitoType>(_ServicoTypeRequisitosRequisito_QNAME, RequisitoType.class, ServicoType.Requisitos.class, value);
    }

}
