//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.31 at 11:03:16 AM BRT 
//


package br.gov.servicos.v3.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AreaDeInteresse.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AreaDeInteresse">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Abastecimento"/>
 *     &lt;enumeration value="Administração financeira"/>
 *     &lt;enumeration value="Agricultura orgânica"/>
 *     &lt;enumeration value="Agropecuária"/>
 *     &lt;enumeration value="Águas"/>
 *     &lt;enumeration value="Alimento"/>
 *     &lt;enumeration value="Ambiente e saúde"/>
 *     &lt;enumeration value="Comunicações"/>
 *     &lt;enumeration value="Comércio e Serviços"/>
 *     &lt;enumeration value="Economia e Finanças"/>
 *     &lt;enumeration value="Educação"/>
 *     &lt;enumeration value="Educação básica"/>
 *     &lt;enumeration value="Educação superior"/>
 *     &lt;enumeration value="Educação à distância"/>
 *     &lt;enumeration value="Emergências e Urgências"/>
 *     &lt;enumeration value="Encargos financeiros"/>
 *     &lt;enumeration value="Esporte e Lazer"/>
 *     &lt;enumeration value="Finanças"/>
 *     &lt;enumeration value="Habitação"/>
 *     &lt;enumeration value="Humanização na saúde"/>
 *     &lt;enumeration value="Indústria"/>
 *     &lt;enumeration value="Meio ambiente"/>
 *     &lt;enumeration value="Pecuária"/>
 *     &lt;enumeration value="Pessoa"/>
 *     &lt;enumeration value="Previdência Social"/>
 *     &lt;enumeration value="Profissionais da educação"/>
 *     &lt;enumeration value="Proteção social"/>
 *     &lt;enumeration value="Qualidade ambiental"/>
 *     &lt;enumeration value="Relações Internacionais"/>
 *     &lt;enumeration value="Saúde"/>
 *     &lt;enumeration value="Saúde da criança"/>
 *     &lt;enumeration value="Saúde da família"/>
 *     &lt;enumeration value="Saúde da mulher"/>
 *     &lt;enumeration value="Saúde do homem"/>
 *     &lt;enumeration value="Saúde do idoso"/>
 *     &lt;enumeration value="Saúde dos portadores de deficiências"/>
 *     &lt;enumeration value="Segurança e Ordem Pública"/>
 *     &lt;enumeration value="Trabalho"/>
 *     &lt;enumeration value="Transportes"/>
 *     &lt;enumeration value="Turismo"/>
 *     &lt;enumeration value="Urbanismo"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AreaDeInteresse")
@XmlEnum
public enum AreaDeInteresse {

    @XmlEnumValue("Abastecimento")
    ABASTECIMENTO("Abastecimento"),
    @XmlEnumValue("Administra\u00e7\u00e3o financeira")
    ADMINISTRAÇÃO_FINANCEIRA("Administra\u00e7\u00e3o financeira"),
    @XmlEnumValue("Agricultura org\u00e2nica")
    AGRICULTURA_ORGÂNICA("Agricultura org\u00e2nica"),
    @XmlEnumValue("Agropecu\u00e1ria")
    AGROPECUÁRIA("Agropecu\u00e1ria"),
    @XmlEnumValue("\u00c1guas")
    ÁGUAS("\u00c1guas"),
    @XmlEnumValue("Alimento")
    ALIMENTO("Alimento"),
    @XmlEnumValue("Ambiente e sa\u00fade")
    AMBIENTE_E_SAÚDE("Ambiente e sa\u00fade"),
    @XmlEnumValue("Comunica\u00e7\u00f5es")
    COMUNICAÇÕES("Comunica\u00e7\u00f5es"),
    @XmlEnumValue("Com\u00e9rcio e Servi\u00e7os")
    COMÉRCIO_E_SERVIÇOS("Com\u00e9rcio e Servi\u00e7os"),
    @XmlEnumValue("Economia e Finan\u00e7as")
    ECONOMIA_E_FINANÇAS("Economia e Finan\u00e7as"),
    @XmlEnumValue("Educa\u00e7\u00e3o")
    EDUCAÇÃO("Educa\u00e7\u00e3o"),
    @XmlEnumValue("Educa\u00e7\u00e3o b\u00e1sica")
    EDUCAÇÃO_BÁSICA("Educa\u00e7\u00e3o b\u00e1sica"),
    @XmlEnumValue("Educa\u00e7\u00e3o superior")
    EDUCAÇÃO_SUPERIOR("Educa\u00e7\u00e3o superior"),
    @XmlEnumValue("Educa\u00e7\u00e3o \u00e0 dist\u00e2ncia")
    EDUCAÇÃO_À_DISTÂNCIA("Educa\u00e7\u00e3o \u00e0 dist\u00e2ncia"),
    @XmlEnumValue("Emerg\u00eancias e Urg\u00eancias")
    EMERGÊNCIAS_E_URGÊNCIAS("Emerg\u00eancias e Urg\u00eancias"),
    @XmlEnumValue("Encargos financeiros")
    ENCARGOS_FINANCEIROS("Encargos financeiros"),
    @XmlEnumValue("Esporte e Lazer")
    ESPORTE_E_LAZER("Esporte e Lazer"),
    @XmlEnumValue("Finan\u00e7as")
    FINANÇAS("Finan\u00e7as"),
    @XmlEnumValue("Habita\u00e7\u00e3o")
    HABITAÇÃO("Habita\u00e7\u00e3o"),
    @XmlEnumValue("Humaniza\u00e7\u00e3o na sa\u00fade")
    HUMANIZAÇÃO_NA_SAÚDE("Humaniza\u00e7\u00e3o na sa\u00fade"),
    @XmlEnumValue("Ind\u00fastria")
    INDÚSTRIA("Ind\u00fastria"),
    @XmlEnumValue("Meio ambiente")
    MEIO_AMBIENTE("Meio ambiente"),
    @XmlEnumValue("Pecu\u00e1ria")
    PECUÁRIA("Pecu\u00e1ria"),
    @XmlEnumValue("Pessoa")
    PESSOA("Pessoa"),
    @XmlEnumValue("Previd\u00eancia Social")
    PREVIDÊNCIA_SOCIAL("Previd\u00eancia Social"),
    @XmlEnumValue("Profissionais da educa\u00e7\u00e3o")
    PROFISSIONAIS_DA_EDUCAÇÃO("Profissionais da educa\u00e7\u00e3o"),
    @XmlEnumValue("Prote\u00e7\u00e3o social")
    PROTEÇÃO_SOCIAL("Prote\u00e7\u00e3o social"),
    @XmlEnumValue("Qualidade ambiental")
    QUALIDADE_AMBIENTAL("Qualidade ambiental"),
    @XmlEnumValue("Rela\u00e7\u00f5es Internacionais")
    RELAÇÕES_INTERNACIONAIS("Rela\u00e7\u00f5es Internacionais"),
    @XmlEnumValue("Sa\u00fade")
    SAÚDE("Sa\u00fade"),
    @XmlEnumValue("Sa\u00fade da crian\u00e7a")
    SAÚDE_DA_CRIANÇA("Sa\u00fade da crian\u00e7a"),
    @XmlEnumValue("Sa\u00fade da fam\u00edlia")
    SAÚDE_DA_FAMÍLIA("Sa\u00fade da fam\u00edlia"),
    @XmlEnumValue("Sa\u00fade da mulher")
    SAÚDE_DA_MULHER("Sa\u00fade da mulher"),
    @XmlEnumValue("Sa\u00fade do homem")
    SAÚDE_DO_HOMEM("Sa\u00fade do homem"),
    @XmlEnumValue("Sa\u00fade do idoso")
    SAÚDE_DO_IDOSO("Sa\u00fade do idoso"),
    @XmlEnumValue("Sa\u00fade dos portadores de defici\u00eancias")
    SAÚDE_DOS_PORTADORES_DE_DEFICIÊNCIAS("Sa\u00fade dos portadores de defici\u00eancias"),
    @XmlEnumValue("Seguran\u00e7a e Ordem P\u00fablica")
    SEGURANÇA_E_ORDEM_PÚBLICA("Seguran\u00e7a e Ordem P\u00fablica"),
    @XmlEnumValue("Trabalho")
    TRABALHO("Trabalho"),
    @XmlEnumValue("Transportes")
    TRANSPORTES("Transportes"),
    @XmlEnumValue("Turismo")
    TURISMO("Turismo"),
    @XmlEnumValue("Urbanismo")
    URBANISMO("Urbanismo");
    private final String value;

    AreaDeInteresse(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AreaDeInteresse fromValue(String v) {
        for (AreaDeInteresse c: AreaDeInteresse.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
