//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.31 at 11:03:16 AM BRT 
//


package br.gov.servicos.v3.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TempoTotalEstimado complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TempoTotalEstimado">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="entre" type="{http://servicos.gov.br/v3/schema}Entre"/>
 *           &lt;element name="ate" type="{http://servicos.gov.br/v3/schema}Ate"/>
 *         &lt;/choice>
 *         &lt;element name="descricao" type="{http://servicos.gov.br/v3/schema}DescricaoDoTempoTotalEstimado"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TempoTotalEstimado", propOrder = {
    "entre",
    "ate",
    "descricao"
})
public class TempoTotalEstimado {

    protected Entre entre;
    protected Ate ate;
    @XmlElement(required = true)
    protected String descricao;

    /**
     * Gets the value of the entre property.
     * 
     * @return
     *     possible object is
     *     {@link Entre }
     *     
     */
    public Entre getEntre() {
        return entre;
    }

    /**
     * Sets the value of the entre property.
     * 
     * @param value
     *     allowed object is
     *     {@link Entre }
     *     
     */
    public void setEntre(Entre value) {
        this.entre = value;
    }

    /**
     * Gets the value of the ate property.
     * 
     * @return
     *     possible object is
     *     {@link Ate }
     *     
     */
    public Ate getAte() {
        return ate;
    }

    /**
     * Sets the value of the ate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ate }
     *     
     */
    public void setAte(Ate value) {
        this.ate = value;
    }

    /**
     * Gets the value of the descricao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescricao() {
        return descricao;
    }

    /**
     * Sets the value of the descricao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescricao(String value) {
        this.descricao = value;
    }

}
