#!/bin/bash

echo "Adicionando repositório Yum do Guia de Serviços..."
cat <<-EOF > /etc/yum.repos.d/guia-de-servicos.repo
[guia-de-servicos]
name = Guia de Serviços
baseurl = https://s3-sa-east-1.amazonaws.com/servicosgovbr/centos/7/
enabled=1
gpgcheck=1
gpgkey=https://raw.githubusercontent.com/servicosgovbr/guia-de-servicos/master/src/main/resources/static/GPG-KEY
EOF

echo 'Atualizando repositório Yum'
yum makecache fast -y
yum remove puppet -y
yum update -y
yum install epel-release haproxy lsof git wget augeas rpm-build -y

# Remove obrigação de TTY para sudoers em deployments automáticos
augtool set '/files/etc/sudoers/Defaults[*]/requiretty/negate' ''

echo 'Baixando JDK'
wget \
    --quiet \
    --no-cookies \
    --no-check-certificate \
    --header 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie' \
    'http://download.oracle.com/otn-pub/java/jdk/8u40-b25/jdk-8u40-linux-x64.rpm'

$(rpm -qa | grep -q jdk1.8.0_40-1.8.0_40-fcs.x86_64) || \
  (echo 'Instalando JDK' && sudo yum install -y 'jdk-8u40-linux-x64.rpm')

$(java -version 2>&1 | grep -q "1.8.0_40") || \
  (echo "JDK não foi instalado corretamente" && exit -1)

echo 'Abrindo porta 80 no firewall...'
firewall-cmd --permanent --add-port 80/tcp

echo 'Salvando alterações do firewall...'
firewall-cmd --reload

cat <<-EOF > /etc/haproxy/haproxy.cfg
global
    log 127.0.0.1 local2
    chroot /var/lib/haproxy
    pidfile /var/run/haproxy.pid
    maxconn 4000
    user haproxy
    group haproxy
    daemon
    stats socket /var/lib/haproxy/stats

defaults
    mode http
    log global
    option httplog
    option dontlognull
    option http-server-close
    option forwardfor except 127.0.0.0/8
    option redispatch
    retries 3
    timeout http-request 10s
    timeout queue 1m
    timeout connect 10s
    timeout client 1m
    timeout server 1m
    timeout http-keep-alive 10s
    timeout check 10s
    maxconn 3000

frontend main *:80
    default_backend app

backend app
    balance roundrobin
    server app1 127.0.0.1:8080 check
EOF

sudo systemctl daemon-reload
sudo systemctl enable haproxy
sudo systemctl start haproxy