#!/bin/bash

echo 'Instalando novo Guia de Serviços'
sudo yum install -y guia-de-servicos-latest.rpm

if [ "$?" -ne '0' ]; then
  echo 'Erro na instalação. Abortando...'
  exit -1
fi

echo 'Removendo pacote instalado'
rm -rf guia-de-servicos-latest.rpm

sudo systemctl daemon-reload
sudo systemctl restart guia-de-servicos
