#!/bin/bash

ssh -F .sshconfig alpha <<-EOF
  set -e
  set -x
  set -o pipefail
  pushd tmp/portal-de-servicos
    git checkout master
    git pull --rebase
    git checkout trunk
    git merge master -Xtheirs -m "Merge branch 'master' into trunk"
    git svn dcommit
  popd
EOF