#!/bin/bash

function instalar_jdk() {
  mkdir -p /vagrant/tmp
  pushd /vagrant/tmp > /dev/null
    if [ -f 'jdk-8u40-linux-x64.rpm' ]; then
      echo 'JDK já foi baixado'
    else
      echo 'Baixando JDK'
      wget \
        --quiet \
        --no-cookies \
        --no-check-certificate \
        --header 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie' \
        'http://download.oracle.com/otn-pub/java/jdk/8u40-b25/jdk-8u40-linux-x64.rpm'
    fi

    $(rpm -qa | grep -q jdk1.8.0_40-1.8.0_40-fcs.x86_64) || \
      (echo 'Instalando JDK' && rpm -Uvh 'jdk-8u40-linux-x64.rpm')

    $(java -version 2>&1 | grep -q "1.8.0_40") || \
      (echo "JDK não foi instalado corretamente" && exit -1)

  popd > /dev/null
}

function instalar_elasticsearch() {
  mkdir -p /vagrant/tmp
  pushd /vagrant/tmp > /dev/null
    if [ -f elasticsearch-1.5.0.noarch.rpm ]; then
      echo 'ElasticSearch já foi baixado'
    else
      echo 'Baixando ElasticSearch'
      wget -c \
        --quiet \
        --no-check-certificate \
        https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.5.0.noarch.rpm
    fi

    $(rpm -qa | grep -q elasticsearch-1.5.0-1.noarch) || \
      (echo 'Instalando ElasticSearch' && rpm -Uvh elasticsearch-1.5.0.noarch.rpm)
  popd > /dev/null

  IP=`case "$1" in es1) echo '10.133.133.22'; ;; es2) echo '10.133.133.33'; ;; esac`
  cat <<-EOF > /etc/elasticsearch/elasticsearch.yml
# Anuncia o IP da rede interna (${IP})
network.publish_host: ${IP}
# Adiciona es1 e es2 ao cluster
discovery.zen.ping.unicast.hosts: ["10.133.133.22:9300", "10.133.133.33:9300"]
EOF

  systemctl daemon-reload
  systemctl enable elasticsearch.service
  systemctl start elasticsearch.service
}