#!/usr/bin/env bash

set -e
set -o pipefail

aws ec2 run-instances \
    --image-id ami-bf9520a2 \
    --count 1 \
    --instance-type t2.micro \
    --key-name cvillela \
    --security-group-ids sg-66185403 \
    --subnet-id subnet-749a752d \
    --associate-public-ip-address \
    --user-data "$(base64 scripts/alpha-bootstrap)"
