#!/bin/bash bash

set -e
set -o pipefail

aws ec2 run-instances \
    --image-id ami-bf9520a2 \
    --count 1 \
    --instance-type t2.micro \
    --key-name guiadeservicos-kp \
    --security-group-ids sg-6e8a6b0b \
    --subnet-id subnet-7ba9481e \
    --associate-public-ip-address \
    --user-data "$(base64 scripts/alpha-bootstrap)"
