#!/bin/bash

echo "Adicionando repositório Yum do Guia de Serviços..."
cat <<-EOF > /etc/yum.repos.d/guia-de-servicos.repo
[guia-de-servicos]
name = Guia de Serviços
baseurl = https://s3-sa-east-1.amazonaws.com/servicosgovbr/centos/7/
enabled=1
gpgcheck=1
gpgkey=https://raw.githubusercontent.com/servicosgovbr/guia-de-servicos/master/src/main/resources/static/GPG-KEY
EOF

echo 'Atualizando repositório Yum'
yum makecache fast -y
yum update -y
yum install epel-release lsof wget augeas -y

# Remove obrigação de TTY para sudoers em deployments automáticos
augtool set '/files/etc/sudoers/Defaults[*]/requiretty/negate' ''

echo 'Baixando JDK'
wget \
    --quiet \
    --no-cookies \
    --no-check-certificate \
    --header 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie' \
    'http://download.oracle.com/otn-pub/java/jdk/8u40-b25/jdk-8u40-linux-x64.rpm'

$(rpm -qa | grep -q jdk1.8.0_40-1.8.0_40-fcs.x86_64) || \
  (echo 'Instalando JDK' && sudo yum install -y 'jdk-8u40-linux-x64.rpm')

$(java -version 2>&1 | grep -q "1.8.0_40") || \
  (echo "JDK não foi instalado corretamente" && exit -1)

echo 'Instalando Guia de Serviços...'
yum install -y guia-de-servicos

echo 'Recarregando daemons...'
systemctl daemon-reload

echo 'Iniciando Guia de Serviços...'
systemctl start guia-de-servicos