#!/bin/bash
set -x
set -e
set -o pipefail

ssh -F .sshconfig dev '/bin/bash -s' << "EOF"
set -x
set -e
set -o pipefail

cd '/root/docker'
git status
git diff
git stash || true
git pull --rebase
git stash pop || true

export PDS_CARTAS_REPOSITORIO='https://github.com/servicosgovbr/cartas-de-teste.git'

export SNAP_API_KEY="${SNAP_API_KEY}"
export SNAP_PIPELINE_COUNTER="${SNAP_PIPELINE_COUNTER}"

./scripts/update_portal_container

EOF
