#!/bin/bash
set -x
set -e
set -o pipefail

ssh -F .sshconfig alpha 'sudo /bin/bash -s' << "EOF"
set -x
set -e
set -o pipefail

cd '/root/docker'
git pull --rebase


docker rm -v $(docker ps -a -q -f status=exited)
docker rmi $(docker images -f "dangling=true" -q)

docker-compose stop portal1 portal2
docker-compose kill portal1 portal2
docker-compose rm -f portal1 portal2

./build portal-de-servicos

docker-compose up -d
docker-compose restart balanceador

EOF
