#!/bin/bash
set -x
set -e
set -o pipefail

ssh -F .sshconfig alpha 'sudo /bin/bash -s' << "EOF"
set -x
set -e
set -o pipefail

cd '/root/docker'
git pull --rebase

./build portal-de-servicos

docker-compose up -d
docker-compose restart balanceador portal1 portal2

EOF
