#!/bin/bash
set -x
set -e
set -o pipefail

ssh -F .sshconfig dev '/bin/bash -s' << "EOF"
set -x
set -e
set -o pipefail

cd '/root/docker'
git pull --rebase

export PDS_CARTAS_REPOSITORIO='https://github.com/servicosgovbr/cartas-de-teste.git'
export EDS_CARTAS_REPOSITORIO='git@github.com:servicosgovbr/cartas-de-teste.git'

docker-compose stop portal1 portal2
docker-compose kill portal1 portal2
docker-compose rm -f portal1 portal2

./build-all

docker-compose up -d
docker-compose restart balanceador

EOF
