#!/bin/bash
set -x
set -e
set -o pipefail

ssh -F .sshconfig alpha 'sudo /bin/bash -s' <<-EOF
yum install "guia-de-servicos-1.0.${SNAP_PIPELINE_COUNTER:-0}-1"
systemctl daemon-reload
systemctl restart guia-de-servicos
EOF
