#!/bin/bash

source "$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)/vagrant-bootstrap-functions"

cat <<-EOF > /etc/yum.repos.d/guia-de-servicos.repo
[guia-de-servicos]
name = Guia de Serviços
baseurl = https://s3-sa-east-1.amazonaws.com/servicosgovbr/centos/7/
enabled=1
gpgcheck=1
gpgkey=https://raw.githubusercontent.com/servicosgovbr/guia-de-servicos/master/src/main/resources/static/GPG-KEY
EOF

echo 'Atualizando repositório Yum'
yum makecache fast -y
yum remove puppet -y
yum update -y
yum install epel-release haproxy lsof git rpm-build augeas -y

# Remove obrigação de TTY para sudoers em deployments automáticos
augtool set '/files/etc/sudoers/Defaults[*]/requiretty/negate' ''

instalar_jdk

echo "Modificando hostname para '${1}'..."
hostname $1

echo 'Abrindo porta 80 no firewall...'
firewall-cmd --permanent --add-port 80/tcp

echo 'Salvando alterações do firewall...'
firewall-cmd --reload

cat <<-EOF > /etc/haproxy/haproxy.cfg
global
    log 127.0.0.1 local2
    chroot /var/lib/haproxy
    pidfile /var/run/haproxy.pid
    maxconn 4000
    user haproxy
    group haproxy
    daemon
    stats socket /var/lib/haproxy/stats

defaults
    mode http
    log global
    option httplog
    option dontlognull
    option http-server-close
    option forwardfor except 127.0.0.0/8
    option redispatch
    retries 3
    timeout http-request 10s
    timeout queue 1m
    timeout connect 10s
    timeout client 1m
    timeout server 1m
    timeout http-keep-alive 10s
    timeout check 10s
    maxconn 3000

frontend main *:80
    default_backend app

backend app
    balance roundrobin
    server app1 127.0.0.1:8080 check
EOF

sudo systemctl daemon-reload
sudo systemctl daemon-reload
sudo systemctl enable haproxy
sudo systemctl start haproxy
