#!/bin/bash

source "$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)/common-bootstrap-functions"

echo 'Atualizando repositório Yum'
yum makecache fast -y
yum remove puppet -y
yum update -y
yum install lsof git rpm-build -y

instalar_jdk
instalar_elasticsearch

hostname $1
firewall-cmd --permanent --add-port 9200/tcp
firewall-cmd --permanent --add-port 9300/tcp
firewall-cmd --reload
