#!/bin/bash

source "$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)/common-bootstrap-functions"

echo 'Atualizando repositório Yum'
yum makecache fast -y
yum remove puppet -y
yum update -y
yum install git rpm-build -y

instalar_jdk
