#!/bin/bash

source "$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)/common-bootstrap-functions"

echo 'Atualizando repositório Yum'
yum makecache fast -y
yum remove puppet -y
yum update -y
yum install lsof git rpm-build -y

instalar_jdk
instalar_elasticsearch

echo "Modificando hostname para '${1}'..."
hostname $1

echo 'Abrindo portas 9200 e 9300 no firewall...'
firewall-cmd --permanent --add-port 9200/tcp
firewall-cmd --permanent --add-port 9300/tcp

echo 'Salvando alterações do firewall...'
firewall-cmd --reload
