#!/bin/bash

echo 'Instalando novo Guia de Serviços...'
sudo yum remove -y guia-de-servicos
sudo yum install -y $1

sudo bash -c 'cat <<-EOF > /etc/sysconfig/guia-de-servicos
# Variáveis de ambiente para configuração do Guia de Serviços

# Ativa os perfis "cluster" e "vagrant" na configuração do Spring.
# - cluster: conecta a um ElasticSearch externo (desliga o ElasticSearch embarcado)
# - vagrant: configura IPs para o ElasticSearch de acordo com o Vagrantfile
#
SPRING_PROFILES_ACTIVE=cluster,vagrant

EOF
'

echo 'Reiniciando serviço...'
sudo systemctl daemon-reload
sudo systemctl restart guia-de-servicos
