#!/bin/bash

source "$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)/common-bootstrap-functions"

echo 'Atualizando repositório Yum'
yum makecache fast -y
yum remove puppet -y
yum update -y
yum install lsof git rpm-build -y

instalar_jdk

echo "Modificando hostname para '${1}'..."
hostname $1

echo 'Abrindo porta 80 no firewall...'
firewall-cmd --permanent --add-port 80/tcp

echo 'Salvando alterações do firewall...'
firewall-cmd --reload
