#!/bin/bash

if [ "$(whoami)" != "root" ]; then
  echo 'Este script deve ser executado como super-usuário (root).'
  exit -1
fi

set -x
set -e
set -o pipefail

echo 'Atualizando repositórios Yum...'
yum makecache fast -y

echo "Fazendo backup das configurações..."
cp /etc/sysconfig/guia-de-servicos-overrides /tmp/guia-de-servicos-overrides.backup

echo 'Instalando Guia de Serviços...'
yum update guia-de-servicos -y

echo "Restaurando backup das configurações..."
mv /tmp/guia-de-servicos-overrides.backup /etc/sysconfig/guia-de-servicos-overrides

echo 'Recarregando daemons...'
systemctl daemon-reload

echo 'Reiniciando Guia de Serviços...'
systemctl restart guia-de-servicos
