#!/bin/bash

if [ "$(whoami)" != "root" ]; then
  echo 'Este script deve ser executado como super-usuário (root).'
  exit -1
fi

set -x
set -e
set -o pipefail

echo 'Atualizando repositórios Yum...'
yum makecache fast -y

echo "Fazendo backup das configurações..."
cp /etc/sysconfig/portal-de-servicos-overrides /tmp/portal-de-servicos-overrides.backup

if [ -z "$1" ]; then
  echo 'Instalando a versão mais recente do Portal de Serviços...'
  yum update portal-de-servicos -y
else
  echo "Instalando Portal de Serviços versão $1..."
  yum update "portal-de-servicos-1.0.${1}-1" -y
fi

echo "Restaurando backup das configurações..."
mv /tmp/portal-de-servicos-overrides.backup /etc/sysconfig/portal-de-servicos-overrides

echo 'Recarregando daemons...'
systemctl daemon-reload

echo 'Reiniciando Portal de Serviços...'
systemctl restart portal-de-servicos
