#!/bin/bash

if [ "$(whoami)" != "root" ]; then
  echo 'Este script deve ser executado como super-usuário (root).'
  exit -1
fi

set -x
set -e
set -o pipefail

# Endereços dos servidores do ElasticSearch
ES_1_IP_ADDR="${1:-10.16.0.11}"
ES_2_IP_ADDR="${2:-10.16.0.9}"

echo 'Adicionando chave GPG do repositório do Guia de Serviços...'
rpm --import https://raw.githubusercontent.com/servicosgovbr/guia-de-servicos/master/src/main/resources/static/GPG-KEY

echo "Adicionando repositório Yum do Guia de Serviços..."
cat <<-EOF > /etc/yum.repos.d/guia-de-servicos.repo
[guia-de-servicos]
name = Guia de Serviços
baseurl = https://s3-sa-east-1.amazonaws.com/servicosgovbr/centos/7/
enabled = 1
gpgcheck = 1
gpgkey = https://raw.githubusercontent.com/servicosgovbr/guia-de-servicos/master/src/main/resources/static/GPG-KEY
EOF

echo 'Atualizando repositório Yum'
yum makecache fast -y
yum install -y wget deltarpm

echo 'Verificando instalação da JDK...'
if [ "$(rpm -q jdk1.8.0_40)" != "jdk1.8.0_40-1.8.0_40-fcs.x86_64" ]; then
  echo 'Baixando JDK'
  wget \
    --quiet \
    --no-cookies \
    --no-check-certificate \
    --timestamping \
    --directory-prefix=/var/cache/wget \
    --header 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie' \
    'http://download.oracle.com/otn-pub/java/jdk/8u40-b25/jdk-8u40-linux-x64.rpm'

  if [ "$(sha1sum '/var/cache/wget/jdk-8u40-linux-x64.rpm' | cut -f 1 -d ' ')" != "1e91457271dbc86ede56432a461b70bff79e19b2" ]; then
    echo "JDK possui checksum incorreto. Verifique que o download foi concluído com sucesso."
    exit -1
  fi

  echo 'Instalando JDK'
  yum install -y '/var/cache/wget/jdk-8u40-linux-x64.rpm'
fi

echo 'Instalando Guia de Serviços...'
yum install -y guia-de-servicos

echo 'Configurando Guia de Serviços...'
cat <<-EOF > /etc/sysconfig/guia-de-servicos
# Guia de Serviços
#
# Este arquivo contém variáveis de ambiente utilizadas na configuração do Guia de Serviços.
# Para mais informações, veja a documentação em:
#
# http://servicosgovbr.github.io/guia-de-servicos/desenvolvimento/configuracao.html
#
SPRING_DATA_ELASTICSEARCH_CLUSTERNODES="${ES_1_IP_ADDR}:9300,${ES_2_IP_ADDR}:9300"
EOF

echo 'Recarregando daemons...'
systemctl daemon-reload

echo 'Habilitando Guia de Serviços para iniciar no boot...'
systemctl enable guia-de-servicos

echo 'Iniciando Guia de Serviços...'
systemctl start guia-de-servicos
