#!/bin/bash

if [ "$(whoami)" != "root" ]; then
  echo 'Este script deve ser executado como super-usuário (root).'
  exit -1
fi

set -x
set -e
set -o pipefail

# Endereços dos servidores do ElasticSearch
ES_1_IP_ADDR="${1:-10.16.0.11}"
ES_2_IP_ADDR="${2:-10.16.0.9}"

echo 'Adicionando chave GPG do repositório do Portal de Serviços...'
rpm --import https://raw.githubusercontent.com/servicosgovbr/portal-de-servicos/master/src/main/resources/static/GPG-KEY

echo "Adicionando repositório Yum do Portal de Serviços..."
cat <<-EOF > /etc/yum.repos.d/portal-de-servicos.repo
[portal-de-servicos]
name = Portal de Serviços
baseurl = https://s3-sa-east-1.amazonaws.com/servicosgovbr/centos/7/
enabled = 1
gpgcheck = 1
gpgkey = https://raw.githubusercontent.com/servicosgovbr/portal-de-servicos/master/src/main/resources/static/GPG-KEY
EOF

echo 'Atualizando repositório Yum'
yum makecache fast -y
yum install -y wget deltarpm

echo 'Verificando instalação da JDK...'
if [ "$(rpm -q jdk1.8.0_40)" != "jdk1.8.0_40-1.8.0_40-fcs.x86_64" ]; then
  echo 'Baixando JDK'
  wget \
    --quiet \
    --no-cookies \
    --no-check-certificate \
    --timestamping \
    --directory-prefix=/var/cache/wget \
    --header 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie' \
    'http://download.oracle.com/otn-pub/java/jdk/8u40-b25/jdk-8u40-linux-x64.rpm'

  if [ "$(sha1sum '/var/cache/wget/jdk-8u40-linux-x64.rpm' | cut -f 1 -d ' ')" != "1e91457271dbc86ede56432a461b70bff79e19b2" ]; then
    echo "JDK possui checksum incorreto. Verifique que o download foi concluído com sucesso."
    exit -1
  fi

  echo 'Instalando JDK'
  yum install -y '/var/cache/wget/jdk-8u40-linux-x64.rpm'
fi

echo 'Instalando Portal de Serviços...'
yum install -y portal-de-servicos

echo 'Configurando Portal de Serviços...'
cat <<-EOF > /etc/sysconfig/portal-de-servicos-overrides
# Este arquivo sobrescreve variáveis de configuração do Portal de Serviços.
# Para mais informações, veja a documentação em:
#
# http://servicosgovbr.github.io/portal-de-servicos/desenvolvimento/configuracao.html
#
SPRING_DATA_ELASTICSEARCH_CLUSTERNODES="${ES_1_IP_ADDR}:9300,${ES_2_IP_ADDR}:9300"
EOF

echo 'Recarregando daemons...'
systemctl daemon-reload

echo 'Habilitando Portal de Serviços para iniciar no boot...'
systemctl enable portal-de-servicos

echo 'Iniciando Portal de Serviços...'
systemctl start portal-de-servicos
