#!/bin/bash

if [ "$(whoami)" != "root" ]; then
  echo 'Este script deve ser executado como super-usuário (root).'
  exit -1
fi

set -x
set -e
set -o pipefail

echo 'Instalando Guia de Serviços...'
yum update -y guia-de-servicos

echo 'Recarregando daemons...'
systemctl daemon-reload

echo 'Reiniciando Guia de Serviços...'
systemctl restart guia-de-servicos
