#!/bin/bash

if [ "$(whoami)" != "root" ]; then
  echo 'Este script deve ser executado como super-usuário (root).'
  exit -1
fi

set -x
set -e
set -o pipefail

echo 'Adicionando chave GPG do repositório do ElasticSearch...'
rpm --import https://packages.elasticsearch.org/GPG-KEY-elasticsearch

echo "Adicionando repositório Yum do ElasticSearch..."
cat <<-EOF > /etc/yum.repos.d/elasticsearch.repo
[elasticsearch-1.5]
name = Elasticsearch repository for 1.5.x packages
baseurl = http://packages.elasticsearch.org/elasticsearch/1.5/centos
enabled = 1
gpgcheck = 1
gpgkey = http://packages.elasticsearch.org/GPG-KEY-elasticsearch
EOF

echo 'Atualizando repositório Yum...'
yum makecache fast -y
yum update -y

echo 'Instalando pacote do ElasticSearch...'
yum install elasticsearch -y

echo 'Recarregando daemons...'
systemctl daemon-reload

echo 'Habilitando ElasticSearch para iniciar no boot...'
systemctl enable elasticsearch

echo 'Iniciando ElasticSearch...'
systemctl start elasticsearch
