#!/bin/bash

if [ "$(whoami)" != "root" ]; then
  echo 'Este script deve ser executado como super-usuário (root).'
  exit -1
fi

set -x
set -e
set -o pipefail

# Endereços dos servidores do ElasticSearch
ES_1_IP_ADDR="${1:-10.16.0.11}"
ES_2_IP_ADDR="${2:-10.16.0.9}"

echo 'Adicionando chave GPG do repositório do ElasticSearch...'
rpm --import https://packages.elasticsearch.org/GPG-KEY-elasticsearch

echo "Adicionando repositório Yum do ElasticSearch..."
cat <<-EOF > /etc/yum.repos.d/elasticsearch.repo
[elasticsearch-1.5]
name = Elasticsearch repository for 1.5.x packages
baseurl = http://packages.elasticsearch.org/elasticsearch/1.5/centos
enabled = 1
gpgcheck = 1
gpgkey = http://packages.elasticsearch.org/GPG-KEY-elasticsearch
EOF

echo 'Atualizando repositório Yum...'
yum makecache fast -y
yum update -y
yum install -y wget

echo 'Verificando instalação da JDK...'
if [ "$(rpm -q jdk1.8.0_40)" != "jdk1.8.0_40-1.8.0_40-fcs.x86_64" ]; then
  echo 'Baixando JDK'
  wget \
    --quiet \
    --no-cookies \
    --no-check-certificate \
    --header 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie' \
    'http://download.oracle.com/otn-pub/java/jdk/8u40-b25/jdk-8u40-linux-x64.rpm'

  if [ "$(sha1sum 'jdk-8u40-linux-x64.rpm' | cut -f 1 -d ' ')" != "1e91457271dbc86ede56432a461b70bff79e19b2" ]; then
    echo "JDK possui checksum incorreto. Verifique que o download foi concluído com sucesso."
    exit -1
  fi

  echo 'Instalando JDK'
  yum install -y 'jdk-8u40-linux-x64.rpm'
fi

echo 'Instalando pacote do ElasticSearch...'
yum install elasticsearch -y

echo 'Configurando ElasticSearch...'
cat <<-EOF > /etc/elasticsearch/elasticsearch.yml
# Publica discovery apenas nesta rede
network.publish_host: ${1}

# Adiciona es1 e es2 ao cluster
discovery.zen.ping.unicast.hosts: ["${ES_1_IP_ADDR}:9300", "${ES_2_IP_ADDR}:9300"]
EOF

echo 'Recarregando daemons...'
systemctl daemon-reload

echo 'Habilitando ElasticSearch para iniciar no boot...'
systemctl enable elasticsearch

echo 'Iniciando ElasticSearch...'
systemctl start elasticsearch
