#!/bin/bash

if [ "$(whoami)" != "root" ]; then
  echo 'Este script deve ser executado como super-usuário (root).'
  exit -1
fi

set -x
set -e
set -o pipefail

# Endereços dos servidores de aplicação do Guia de Serviços
APP_1_IP_ADDR="${1:-10.16.0.13}"
APP_2_IP_ADDR="${2:-10.16.0.12}"

yum makecache fast -y
yum install -y epel-release haproxy

cat <<-EOF > /etc/haproxy/haproxy.cfg
global
    log 127.0.0.1 local2
    chroot /var/lib/haproxy
    pidfile /var/run/haproxy.pid
    maxconn 4000
    user haproxy
    group haproxy
    daemon
    stats socket /var/lib/haproxy/stats

defaults
    mode http
    log global
    option httplog
    option dontlognull
    option http-server-close
    option forwardfor except 127.0.0.0/8
    option redispatch
    retries 3
    timeout http-request 10s
    timeout queue 1m
    timeout connect 10s
    timeout client 1m
    timeout server 1m
    timeout http-keep-alive 10s
    timeout check 10s
    maxconn 3000

frontend main *:80
    default_backend app
    rspadd X-Frame-Options:\ DENY

backend app
    balance roundrobin
    server app1 ${APP_1_IP_ADDR}:8080 check
    server app2 ${APP_2_IP_ADDR}:8080 check
EOF

systemctl daemon-reload
systemctl enable haproxy
systemctl start haproxy