#!/bin/bash

if [ "$(whoami)" != "root" ]; then
  echo 'Este script deve ser executado como super-usuário (root).'
  exit -1
fi

set -x
set -e
set -o pipefail

echo 'Atualizando todos os pacotes...'
yum update -y

echo 'Instalando augeas...'
yum install augeas -y

echo 'Configurando /etc/sudoers...'
# Remove obrigação de TTY para sudoers em deployments automáticos
augtool set '/files/etc/sudoers/Defaults[*]/requiretty/negate' ''

echo "Modificando hostname para '${1}'..."
hostname $1

echo 'Reconfigurando Guia de Serviços...'
cat <<-EOF > /etc/sysconfig/guia-de-servicos
# Variáveis de ambiente para configuração do Guia de Serviços

SPRING_PROFILES_ACTIVE=production

EOF

echo 'Recarregando serviços...'
systemctl daemon-reload

echo 'Reiniciando aplicação...'
systemctl restart guia-de-servicos
