#!/bin/bash

if [ "$(whoami)" != "root" ]; then
  echo 'Este script deve ser executado como super-usuário (root).'
  exit -1
fi

set -x
set -e
set -o pipefail

# Endereços dos servidores do ElasticSearch
ES_1_IP_ADDR="${2:-10.16.0.11}"
ES_2_IP_ADDR="${3:-10.16.0.9}"

# Endereço do piwik
PIWIK_ADDR="${4:-10.16.0.181}"


echo 'Instalando novo Guia de Serviços...'
yum remove -y guia-de-servicos
yum install -y /vagrant/build/rpmbuild/RPMS/noarch/guia-de-servicos-1.0.0-1.noarch.rpm

echo 'Configurando Guia de Serviços...'
cat <<-EOF > /etc/sysconfig/guia-de-servicos-overrides
# Variáveis de ambiente para configuração do Guia de Serviços

SPRING_DATA_ELASTICSEARCH_CLUSTERNODES="${ES_1_IP_ADDR}:9300,${ES_2_IP_ADDR}:9300"

ENDPOINTS_ENABLED=true
ENDPOINTS_HEALTH_SENSITIVE=false

GDS_PIWIK_ENABLED=true
GDS_PIWIK_URL="http://${PIWIK_ADDR}/"
GDS_PIWIK_TOKEN=c0e024d9200b5705bc4804722636378a
GDS_PIWIK_SITE=1
EOF

echo 'Recarregando serviços...'
systemctl daemon-reload

echo 'Reiniciando aplicação...'
systemctl restart guia-de-servicos
