#!/bin/bash

if [ "$(whoami)" != "root" ]; then
  echo 'Este script deve ser executado como super-usuário (root).'
  exit -1
fi

set -x
set -e
set -o pipefail

echo 'Instalando novo Guia de Serviços...'
yum remove -y guia-de-servicos
yum install -y /vagrant/build/rpmbuild/RPMS/noarch/guia-de-servicos-1.0.0-1.noarch.rpm

echo 'Configurando Guia de Serviços...'
cat <<-EOF > /etc/sysconfig/guia-de-servicos
# Variáveis de ambiente para configuração do Guia de Serviços

SPRING_PROFILES_ACTIVE=production

EOF

echo 'Recarregando serviços...'
systemctl daemon-reload

echo 'Reiniciando aplicação...'
systemctl restart guia-de-servicos
