#!/bin/bash

set -x
set -e
set -o pipefail

echo 'Instalando novo Guia de Serviços...'
sudo yum remove -y guia-de-servicos
sudo yum install -y /vagrant/build/rpmbuild/RPMS/noarch/guia-de-servicos-1.0.0-1.noarch.rpm

echo 'Configurando variáveis de ambiente...'
sudo bash -c 'cat <<-EOF > /etc/sysconfig/guia-de-servicos
# Ativa os perfis "cluster" e "vagrant" na configuração do Spring.
# - cluster: conecta a um ElasticSearch externo (desliga o ElasticSearch embarcado)
# - vagrant: configura IPs para o ElasticSearch de acordo com o Vagrantfile
#
SPRING_PROFILES_ACTIVE=cluster,vagrant
EOF
'

echo 'Recarregando serviços...'
sudo systemctl daemon-reload

echo 'Reiniciando aplicação...'
sudo systemctl restart guia-de-servicos
