#!/bin/bash

if [ "$(whoami)" != "root" ]; then
  echo 'Este script deve ser executado como super-usuário (root).'
  exit -1
fi

set -x
set -e
set -o pipefail

echo 'Instalando augeas...'
yum install augeas -y

echo 'Configurando /etc/sudoers...'
# Remove obrigação de TTY para sudoers em deployments automáticos
augtool set '/files/etc/sudoers/Defaults[*]/requiretty/negate' ''

echo "Modificando hostname para '${1}'..."
hostname $1

echo 'Abrindo portas 9200 e 9300 no firewall...'
firewall-cmd --permanent --add-port 9200/tcp
firewall-cmd --permanent --add-port 9300/tcp

echo 'Salvando alterações do firewall...'
firewall-cmd --reload
